### ISSUE TITLE
insert-annotations-to-source command-line options

### ISSUE THREAD

**Issue by wmdietl** [typetools/annotation-tools#120]
The -h output of insert-annotations-to-source says:

  -d --outdir=<directory>       - Directory in which output files are written [default annotated/]

When I call it with `-d out/` I get the error:

```
--- end of insert-annotations-to-source debugging output
Exception in thread "main" java.lang.Error: Unrecognized file extension: out/
	at annotator.Main.main(Main.java:629)
```

One has to write `-d=out/` or the long form `--outdir=out/`.

This violates the standard Unix command-line options syntax.

**Comment by dbrosoft** [comment]
It seems that "-d" without "=" is interpreted as an abbreviation of "--debug".  I don't know whether that comports with the expected behavior for `plume.Option`.  @mernst?

**Comment by mernst** [comment]
The script insert-annotations-to-source interprets a leading -d as an indication that the script itself should be debugged.  The -d is stripped off and never passed to the underlying Java program nor to plume.Options.

I have changed it to use --debug-script instead of -d, on the theory that --debug-script is less likely to collide with command-line options used by the underlying programs.
