### ISSUE TITLE
Support command line options to limit inserted annotations

### ISSUE THREAD

**Issue by GoogleCodeExporter** [typetools/annotation-tools#70]
```
A couple of new command line options would make it possible to insert only 
annotations that have an effect, i.e. annotations that are not the default.

These would be tailored to work with the CLIMB convention.

1) Do not insert a specified annotation into CLIMB locations.
2) Do not insert a specified annotation into NON-CLIMB locations.

For the nullness type system, you would use these options to ensure that the 
annotations inserted differ from the default. (These names need work).

--ignore-climb-annotations-of @Nullable
--ignore-non-climb-annotations-of @NonNull

These options could also be expanded take more granular location-annotation 
pairs to ignore to support type systems that don't follow the CLIMB convention.

```

Original issue reported on code.google.com by `mcart...@cs.washington.edu` on 20 Dec 2013 at 7:15

**Comment by mernst** [comment]
Moving this functonality into the AFU is a bad idea, because the only tool that knows what the default annotation at a location is the Checker Framework and we don't want to make the AFU depend on the CF.  We will propose a different approach that uses the CF to compile the code to determine the default annotations.  The AFU will have an option in which it reads those default annotations and does not insert them.
